/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufpi.GUI.Cadastro;

import br.edu.ufpi.GUI.Busca.JFrameBuscarCondominio;
import br.edu.ufpi.GUI.Busca.JFrameBuscarContas;
import br.edu.ufpi.GUI.Busca.JFrameBuscarInquilino;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 *
 * @author waldeque
 */
public class JFrameCadastrarCondominio extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
//     CardLayout c1;
    public JFrameCadastrarCondominio() {
        initComponents();
//        c1 = (CardLayout) (jPanelPai.getLayout());
//        c1 = (CardLayout)(jPanelPai.getLayout());
//        this.getContentPane().add(jPanelPai, BorderLayout.CENTER);
//        cards = new JPanel(new CardLayout()); //variável de instancia

        //        jPanelPai.setVisible(true);
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
        jPanelCadastrarCondominio.setVisible(true);
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPai = new JPanel(new CardLayout());
        jPanelCadastrarCondominio = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivoCadastrar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuArquivoCadastrarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarContas = new javax.swing.JMenuItem();
        jMenuArquivoBuscar = new javax.swing.JMenu();
        jMenuArquivoBuscarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoBuscarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoBuscarContas = new javax.swing.JMenuItem();
        jMenuArquivoSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelPai.setVisible(true);

        jPanelCadastrarCondominio.setVisible(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cadastrar Condomínio");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Cadastrar");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Logradouro");

        jLabel13.setText("Número:");

        jLabel14.setText("Nome do Condominio");

        jLabel15.setText("Bairro");

        jLabel16.setText("CEP:");

        jLabel17.setText("Complemento");

        jLabel18.setText("UF");

        jToggleButton5.setText("Cadastrar +");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("Cancelar");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jLabel19.setText("Cidade");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrarCondominioLayout = new javax.swing.GroupLayout(jPanelCadastrarCondominio);
        jPanelCadastrarCondominio.setLayout(jPanelCadastrarCondominioLayout);
        jPanelCadastrarCondominioLayout.setHorizontalGroup(
            jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField8))
                        .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarCondominioLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarCondominioLayout.createSequentialGroup()
                                    .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastrarCondominioLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField11)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField12))
                                        .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jToggleButton6)
                .addGap(29, 29, 29)
                .addComponent(jToggleButton5)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCadastrarCondominioLayout.setVerticalGroup(
            jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarCondominioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanelCadastrarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton4))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        this.getContentPane().add(jPanelPai, BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelPaiLayout = new javax.swing.GroupLayout(jPanelPai);
        jPanelPai.setLayout(jPanelPaiLayout);
        jPanelPaiLayout.setHorizontalGroup(
            jPanelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastrarCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelPaiLayout.setVerticalGroup(
            jPanelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaiLayout.createSequentialGroup()
                .addComponent(jPanelCadastrarCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 914, Short.MAX_VALUE))
        );

        jMenuArquivoCadastrar.setText("Arquivo");

        jMenu3.setText("Cadastrar");

        jMenuArquivoCadastrarCondominio.setText("Condomínio");
        jMenuArquivoCadastrarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarCondominioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarCondominio);

        jMenuArquivoCadastrarInquilino.setText("Inquilino");
        jMenuArquivoCadastrarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarInquilinoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarInquilino);

        jMenuArquivoCadastrarContas.setText("Contas");
        jMenuArquivoCadastrarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarContasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarContas);

        jMenuArquivoCadastrar.add(jMenu3);

        jMenuArquivoBuscar.setText("Buscar");

        jMenuArquivoBuscarCondominio.setText("Condomínio");
        jMenuArquivoBuscarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarCondominioActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarCondominio);

        jMenuArquivoBuscarInquilino.setText("Inquilino");
        jMenuArquivoBuscarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarInquilinoActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarInquilino);

        jMenuArquivoBuscarContas.setText("Contas");
        jMenuArquivoBuscarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarContasActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarContas);

        jMenuArquivoCadastrar.add(jMenuArquivoBuscar);

        jMenuArquivoSair.setText("Sair");
        jMenuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivoCadastrar.add(jMenuArquivoSair);

        jMenuBar1.add(jMenuArquivoCadastrar);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArquivoCadastrarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarCondominioActionPerformed
//        jPanelPai = jPanelCadastrarCondominio;
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
//        jPanelPai.setVisible(true);
        JFrameCadastrarCondominio frame = new JFrameCadastrarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoCadastrarCondominioActionPerformed

    private void jMenuArquivoCadastrarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarInquilinoActionPerformed
        JFrameCadastrarInquilino frame = new JFrameCadastrarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
//        
//        

//        c1.show(jPanelPai, "jPanelBuscarInquilino");
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        
//        jPanelPai.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarInquilinoActionPerformed

    private void jMenuArquivoBuscarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarCondominioActionPerformed
        JFrameBuscarCondominio frame = new JFrameBuscarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoBuscarCondominioActionPerformed

    private void jMenuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuArquivoSairActionPerformed

    private void jMenuArquivoCadastrarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarContasActionPerformed
       JFrameCadastrarContas frame = new JFrameCadastrarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarContasActionPerformed

    private void jMenuArquivoBuscarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarInquilinoActionPerformed
        JFrameBuscarInquilino frame = new JFrameBuscarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarInquilinoActionPerformed

    private void jMenuArquivoBuscarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarContasActionPerformed
        JFrameBuscarContas frame = new JFrameBuscarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarContasActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
    Connection connection = null;
    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
    try {  
        java.sql.Statement stmt = connection.createStatement();  
      
        // Prepare a statement to insert a record  
        String sql = "INSERT INTO CONDOMINIOS VALUES(001, "+ " CondominioTeste" + "Rua Amaral Dias" + "1202" + "Vermelha" + "64000400"+ "Teresina" + "PI"+ ")";  
      
        // Execute the insert statement  
        stmt.executeUpdate(sql);  
    } catch (SQLException e) {  
    } 

//       INSERT INTO APP.FRIENDS VALUES
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastrarCondominio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuArquivoBuscar;
    private javax.swing.JMenuItem jMenuArquivoBuscarCondominio;
    private javax.swing.JMenuItem jMenuArquivoBuscarContas;
    private javax.swing.JMenuItem jMenuArquivoBuscarInquilino;
    private javax.swing.JMenu jMenuArquivoCadastrar;
    private javax.swing.JMenuItem jMenuArquivoCadastrarCondominio;
    private javax.swing.JMenuItem jMenuArquivoCadastrarContas;
    private javax.swing.JMenuItem jMenuArquivoCadastrarInquilino;
    private javax.swing.JMenuItem jMenuArquivoSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCadastrarCondominio;
    private javax.swing.JPanel jPanelPai;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
}
