/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufpi.GUI.Cadastro;

import br.edu.ufpi.GUI.Busca.JFrameBuscarCondominio;
import br.edu.ufpi.GUI.Busca.JFrameBuscarContas;
import br.edu.ufpi.GUI.Busca.JFrameBuscarInquilino;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author waldeque
 */
public class JFrameCadastrarGrupoContas extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
//     CardLayout c1;
    public JFrameCadastrarGrupoContas() {
        initComponents();
//        c1 = (CardLayout) (jPanelPai.getLayout());
//        c1 = (CardLayout)(jPanelPai.getLayout());
//        this.getContentPane().add(jPanelPai, BorderLayout.CENTER);
//        cards = new JPanel(new CardLayout()); //variável de instancia

        //        jPanelPai.setVisible(true);
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPai = new JPanel(new CardLayout());
        jPanelCadastrarGrupoContas = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jToggleButton13 = new javax.swing.JToggleButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jLabel54 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivoCadastrar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuArquivoCadastrarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarContas = new javax.swing.JMenuItem();
        jMenuArquivoBuscar = new javax.swing.JMenu();
        jMenuArquivoBuscarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoBuscarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoBuscarContas = new javax.swing.JMenuItem();
        jMenuArquivoSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPai.setVisible(true);

        jPanelCadastrarGrupoContas.setVisible(false);

        jLabel48.setText("Cadastrar Grupo de Contas");

        jToggleButton13.setText("Cadastrar");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jLabel52.setText("Código do Grupo");

        jToggleButton14.setText("Cadastrar +");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton15.setText("Cancelar");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jLabel54.setText("Nome Grupo");

        javax.swing.GroupLayout jPanelCadastrarGrupoContasLayout = new javax.swing.GroupLayout(jPanelCadastrarGrupoContas);
        jPanelCadastrarGrupoContas.setLayout(jPanelCadastrarGrupoContasLayout);
        jPanelCadastrarGrupoContasLayout.setHorizontalGroup(
            jPanelCadastrarGrupoContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarGrupoContasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarGrupoContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarGrupoContasLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrarGrupoContasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelCadastrarGrupoContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastrarGrupoContasLayout.createSequentialGroup()
                                .addComponent(jToggleButton15)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton14)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton13))
                            .addGroup(jPanelCadastrarGrupoContasLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49)
                        .addGap(355, 355, 355))))
        );
        jPanelCadastrarGrupoContasLayout.setVerticalGroup(
            jPanelCadastrarGrupoContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarGrupoContasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarGrupoContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel52)
                    .addComponent(jLabel54)
                    .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(jPanelCadastrarGrupoContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15))
                .addGap(21, 21, 21))
        );

        this.getContentPane().add(jPanelPai, BorderLayout.CENTER);

        javax.swing.GroupLayout jPanelPaiLayout = new javax.swing.GroupLayout(jPanelPai);
        jPanelPai.setLayout(jPanelPaiLayout);
        jPanelPaiLayout.setHorizontalGroup(
            jPanelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaiLayout.createSequentialGroup()
                .addComponent(jPanelCadastrarGrupoContas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 134, Short.MAX_VALUE))
        );
        jPanelPaiLayout.setVerticalGroup(
            jPanelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaiLayout.createSequentialGroup()
                .addComponent(jPanelCadastrarGrupoContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 544, Short.MAX_VALUE))
        );

        jMenuArquivoCadastrar.setText("Arquivo");

        jMenu3.setText("Cadastrar");

        jMenuArquivoCadastrarCondominio.setText("Condomínio");
        jMenuArquivoCadastrarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarCondominioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarCondominio);

        jMenuArquivoCadastrarInquilino.setText("Inquilino");
        jMenuArquivoCadastrarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarInquilinoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarInquilino);

        jMenuArquivoCadastrarContas.setText("Contas");
        jMenuArquivoCadastrarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarContasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarContas);

        jMenuArquivoCadastrar.add(jMenu3);

        jMenuArquivoBuscar.setText("Buscar");

        jMenuArquivoBuscarCondominio.setText("Condomínio");
        jMenuArquivoBuscarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarCondominioActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarCondominio);

        jMenuArquivoBuscarInquilino.setText("Inquilino");
        jMenuArquivoBuscarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarInquilinoActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarInquilino);

        jMenuArquivoBuscarContas.setText("Contas");
        jMenuArquivoBuscarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarContasActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarContas);

        jMenuArquivoCadastrar.add(jMenuArquivoBuscar);

        jMenuArquivoSair.setText("Sair");
        jMenuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivoCadastrar.add(jMenuArquivoSair);

        jMenuBar1.add(jMenuArquivoCadastrar);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArquivoCadastrarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarCondominioActionPerformed
//        jPanelPai = jPanelCadastrarCondominio;
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
//        jPanelPai.setVisible(true);
        JFrameCadastrarCondominio frame = new JFrameCadastrarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoCadastrarCondominioActionPerformed

    private void jMenuArquivoCadastrarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarInquilinoActionPerformed
        JFrameCadastrarInquilino frame = new JFrameCadastrarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
//        
//        

//        c1.show(jPanelPai, "jPanelBuscarInquilino");
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        
//        jPanelPai.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarInquilinoActionPerformed

    private void jMenuArquivoBuscarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarCondominioActionPerformed
        JFrameBuscarCondominio frame = new JFrameBuscarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoBuscarCondominioActionPerformed

    private void jMenuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuArquivoSairActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jMenuArquivoCadastrarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarContasActionPerformed
       JFrameCadastrarContas frame = new JFrameCadastrarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarContasActionPerformed

    private void jMenuArquivoBuscarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarInquilinoActionPerformed
        JFrameBuscarInquilino frame = new JFrameBuscarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarInquilinoActionPerformed

    private void jMenuArquivoBuscarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarContasActionPerformed
        JFrameBuscarContas frame = new JFrameBuscarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarGrupoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarGrupoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarGrupoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarGrupoContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastrarGrupoContas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuArquivoBuscar;
    private javax.swing.JMenuItem jMenuArquivoBuscarCondominio;
    private javax.swing.JMenuItem jMenuArquivoBuscarContas;
    private javax.swing.JMenuItem jMenuArquivoBuscarInquilino;
    private javax.swing.JMenu jMenuArquivoCadastrar;
    private javax.swing.JMenuItem jMenuArquivoCadastrarCondominio;
    private javax.swing.JMenuItem jMenuArquivoCadastrarContas;
    private javax.swing.JMenuItem jMenuArquivoCadastrarInquilino;
    private javax.swing.JMenuItem jMenuArquivoSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCadastrarGrupoContas;
    private javax.swing.JPanel jPanelPai;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    // End of variables declaration//GEN-END:variables
}
