/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufpi.GUI.Busca;

import br.edu.ufpi.GUI.Cadastro.JFrameCadastrarCondominio;
import br.edu.ufpi.GUI.Cadastro.JFrameCadastrarContas;
import br.edu.ufpi.GUI.Cadastro.JFrameCadastrarInquilino;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author waldeque
 */
public class JFrameBuscarInquilino extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
//     CardLayout c1;
    public JFrameBuscarInquilino() {
        initComponents();
//        c1 = (CardLayout) (jPanelPai.getLayout());
//        c1 = (CardLayout)(jPanelPai.getLayout());
//        this.getContentPane().add(jPanelPai, BorderLayout.CENTER);
//        cards = new JPanel(new CardLayout()); //variável de instancia

        //        jPanelPai.setVisible(true);
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
        jPanelBuscarInquilino.setVisible(true);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarInquilino = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivoCadastrar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuArquivoCadastrarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarContas = new javax.swing.JMenuItem();
        jMenuArquivoBuscar = new javax.swing.JMenu();
        jMenuArquivoBuscarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoBuscarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoBuscarContas = new javax.swing.JMenuItem();
        jMenuArquivoSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelBuscarInquilino.setVisible(false);
        jPanelBuscarInquilino.setPreferredSize(new java.awt.Dimension(550, 300));

        jLabel4.setText("Buscar Inquilino");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Buscar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Nome");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("CPF");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "RG", "UF", "Data de Nascimento", "Código Condominio", "Apartamento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("Resultado da Busca");

        javax.swing.GroupLayout jPanelBuscarInquilinoLayout = new javax.swing.GroupLayout(jPanelBuscarInquilino);
        jPanelBuscarInquilino.setLayout(jPanelBuscarInquilinoLayout);
        jPanelBuscarInquilinoLayout.setHorizontalGroup(
            jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarInquilinoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarInquilinoLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBuscarInquilinoLayout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jCheckBox4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarInquilinoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanelBuscarInquilinoLayout.setVerticalGroup(
            jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarInquilinoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4))
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jMenuArquivoCadastrar.setText("Arquivo");

        jMenu3.setText("Cadastrar");

        jMenuArquivoCadastrarCondominio.setText("Condomínio");
        jMenuArquivoCadastrarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarCondominioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarCondominio);

        jMenuArquivoCadastrarInquilino.setText("Inquilino");
        jMenuArquivoCadastrarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarInquilinoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarInquilino);

        jMenuArquivoCadastrarContas.setText("Contas");
        jMenuArquivoCadastrarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarContasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarContas);

        jMenuArquivoCadastrar.add(jMenu3);

        jMenuArquivoBuscar.setText("Buscar");

        jMenuArquivoBuscarCondominio.setText("Condomínio");
        jMenuArquivoBuscarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarCondominioActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarCondominio);

        jMenuArquivoBuscarInquilino.setText("Inquilino");
        jMenuArquivoBuscarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarInquilinoActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarInquilino);

        jMenuArquivoBuscarContas.setText("Contas");
        jMenuArquivoBuscarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarContasActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarContas);

        jMenuArquivoCadastrar.add(jMenuArquivoBuscar);

        jMenuArquivoSair.setText("Sair");
        jMenuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivoCadastrar.add(jMenuArquivoSair);

        jMenuBar1.add(jMenuArquivoCadastrar);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBuscarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );

        //jPanelBuscarInquilino.setLayout(new BorderLayout());
        //jPanelPai.add(jPanelBuscarInquilino, "jPanelBuscarInquilino");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArquivoCadastrarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarCondominioActionPerformed
//        jPanelPai = jPanelCadastrarCondominio;
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
//        jPanelPai.setVisible(true);
        JFrameCadastrarCondominio frame = new JFrameCadastrarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoCadastrarCondominioActionPerformed

    private void jMenuArquivoCadastrarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarInquilinoActionPerformed
        JFrameCadastrarInquilino frame = new JFrameCadastrarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
//        
//        

//        c1.show(jPanelPai, "jPanelBuscarInquilino");
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        
//        jPanelPai.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarInquilinoActionPerformed

    private void jMenuArquivoBuscarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarCondominioActionPerformed
        JFrameBuscarCondominio frame = new JFrameBuscarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoBuscarCondominioActionPerformed

    private void jMenuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuArquivoSairActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jMenuArquivoCadastrarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarContasActionPerformed
       JFrameCadastrarContas frame = new JFrameCadastrarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarContasActionPerformed

    private void jMenuArquivoBuscarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarInquilinoActionPerformed
        JFrameBuscarInquilino frame = new JFrameBuscarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarInquilinoActionPerformed

    private void jMenuArquivoBuscarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarContasActionPerformed
        JFrameBuscarContas frame = new JFrameBuscarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarInquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBuscarInquilino().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuArquivoBuscar;
    private javax.swing.JMenuItem jMenuArquivoBuscarCondominio;
    private javax.swing.JMenuItem jMenuArquivoBuscarContas;
    private javax.swing.JMenuItem jMenuArquivoBuscarInquilino;
    private javax.swing.JMenu jMenuArquivoCadastrar;
    private javax.swing.JMenuItem jMenuArquivoCadastrarCondominio;
    private javax.swing.JMenuItem jMenuArquivoCadastrarContas;
    private javax.swing.JMenuItem jMenuArquivoCadastrarInquilino;
    private javax.swing.JMenuItem jMenuArquivoSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBuscarInquilino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
