/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufpi.GUI.Busca;

import br.edu.ufpi.GUI.Cadastro.JFrameCadastrarCondominio;
import br.edu.ufpi.GUI.Cadastro.JFrameCadastrarContas;
import br.edu.ufpi.GUI.Cadastro.JFrameCadastrarInquilino;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author waldeque
 */
public class JFrameBuscarCondominio extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
//     CardLayout c1;
    public JFrameBuscarCondominio() {
        initComponents();
//        c1 = (CardLayout) (jPanelPai.getLayout());
//        c1 = (CardLayout)(jPanelPai.getLayout());
//        this.getContentPane().add(jPanelPai, BorderLayout.CENTER);
//        cards = new JPanel(new CardLayout()); //variável de instancia

        //        jPanelPai.setVisible(true);
        jPanelBuscarCondominio.setVisible(true);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarCondominio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivoCadastrar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuArquivoCadastrarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoCadastrarContas = new javax.swing.JMenuItem();
        jMenuArquivoBuscar = new javax.swing.JMenu();
        jMenuArquivoBuscarCondominio = new javax.swing.JMenuItem();
        jMenuArquivoBuscarInquilino = new javax.swing.JMenuItem();
        jMenuArquivoBuscarContas = new javax.swing.JMenuItem();
        jMenuArquivoSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelBuscarCondominio.setVisible(false);
        jPanelBuscarCondominio.setPreferredSize(new java.awt.Dimension(550, 550));

        jLabel2.setText("Buscar Condomínio");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Buscar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Nome");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Código");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Resultado da Busca");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Logradouro", "Numero", "Bairro", "CEP", "Complemento", "Cidade", "UF"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelBuscarCondominioLayout = new javax.swing.GroupLayout(jPanelBuscarCondominio);
        jPanelBuscarCondominio.setLayout(jPanelBuscarCondominioLayout);
        jPanelBuscarCondominioLayout.setHorizontalGroup(
            jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarCondominioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(jPanelBuscarCondominioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarCondominioLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBuscarCondominioLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0))
                            .addGroup(jPanelBuscarCondominioLayout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(jPanelBuscarCondominioLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBuscarCondominioLayout.setVerticalGroup(
            jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarCondominioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(911, Short.MAX_VALUE))
        );

        jMenuArquivoCadastrar.setText("Arquivo");

        jMenu3.setText("Cadastrar");

        jMenuArquivoCadastrarCondominio.setText("Condomínio");
        jMenuArquivoCadastrarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarCondominioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarCondominio);

        jMenuArquivoCadastrarInquilino.setText("Inquilino");
        jMenuArquivoCadastrarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarInquilinoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarInquilino);

        jMenuArquivoCadastrarContas.setText("Contas");
        jMenuArquivoCadastrarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoCadastrarContasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuArquivoCadastrarContas);

        jMenuArquivoCadastrar.add(jMenu3);

        jMenuArquivoBuscar.setText("Buscar");

        jMenuArquivoBuscarCondominio.setText("Condomínio");
        jMenuArquivoBuscarCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarCondominioActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarCondominio);

        jMenuArquivoBuscarInquilino.setText("Inquilino");
        jMenuArquivoBuscarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarInquilinoActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarInquilino);

        jMenuArquivoBuscarContas.setText("Contas");
        jMenuArquivoBuscarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoBuscarContasActionPerformed(evt);
            }
        });
        jMenuArquivoBuscar.add(jMenuArquivoBuscarContas);

        jMenuArquivoCadastrar.add(jMenuArquivoBuscar);

        jMenuArquivoSair.setText("Sair");
        jMenuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivoCadastrar.add(jMenuArquivoSair);

        jMenuBar1.add(jMenuArquivoCadastrar);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarCondominio, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarCondominio, javax.swing.GroupLayout.DEFAULT_SIZE, 1345, Short.MAX_VALUE)
        );

        //telaInicial = new JPanel(); //variável de instancia
        //jPanelBuscarCondominio.setLayout(new BorderLayout());
        //jPanelPai.add(jPanelBuscarCondominio, "jPanelBuscarInquilino");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArquivoCadastrarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarCondominioActionPerformed
//        jPanelPai = jPanelCadastrarCondominio;
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        
//        jPanelCadastrarContas.setVisible(false);
//        jPanelCadastrarInquilino.setVisible(false);
//        jPanelPai.setVisible(true);
        JFrameCadastrarCondominio frame = new JFrameCadastrarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoCadastrarCondominioActionPerformed

    private void jMenuArquivoCadastrarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarInquilinoActionPerformed
        JFrameCadastrarInquilino frame = new JFrameCadastrarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
//        
//        

//        c1.show(jPanelPai, "jPanelBuscarInquilino");
//        jPanelBuscarCondominio.setVisible(false);
//        jPanelBuscarContas.setVisible(false);
//        jPanelBuscarInquilino.setVisible(false);
//        jPanelCadastrarCondominio.setVisible(false);
//        jPanelCadastrarContas.setVisible(false);
//        
//        jPanelPai.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarInquilinoActionPerformed

    private void jMenuArquivoBuscarCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarCondominioActionPerformed
        JFrameBuscarCondominio frame = new JFrameBuscarCondominio();
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_jMenuArquivoBuscarCondominioActionPerformed

    private void jMenuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuArquivoSairActionPerformed

    private void jMenuArquivoCadastrarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoCadastrarContasActionPerformed
       JFrameCadastrarContas frame = new JFrameCadastrarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoCadastrarContasActionPerformed

    private void jMenuArquivoBuscarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarInquilinoActionPerformed
        JFrameBuscarInquilino frame = new JFrameBuscarInquilino();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarInquilinoActionPerformed

    private void jMenuArquivoBuscarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoBuscarContasActionPerformed
        JFrameBuscarContas frame = new JFrameBuscarContas();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuArquivoBuscarContasActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBuscarCondominio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBuscarCondominio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuArquivoBuscar;
    private javax.swing.JMenuItem jMenuArquivoBuscarCondominio;
    private javax.swing.JMenuItem jMenuArquivoBuscarContas;
    private javax.swing.JMenuItem jMenuArquivoBuscarInquilino;
    private javax.swing.JMenu jMenuArquivoCadastrar;
    private javax.swing.JMenuItem jMenuArquivoCadastrarCondominio;
    private javax.swing.JMenuItem jMenuArquivoCadastrarContas;
    private javax.swing.JMenuItem jMenuArquivoCadastrarInquilino;
    private javax.swing.JMenuItem jMenuArquivoSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBuscarCondominio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
